set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

"let vundle manage vundle
Plugin 'kien/ctrlp.vim' " fuwwy find files
Plugin 'scrooloose/nerdtree' " file drawer :NerdTreeToggle()
Plugin 'benmills/vimux'
Plugin 'tpope/vim-fugitive' " git helper
Plugin 'tpope/vim-commentary' " git

call vundle#end()
filetype plugin indent on

" adding to the status the current branch
set laststatus=2
set statusline=hello\ Marco\
set statusline+=%#PmenuSel#
set statusline+=\ %{fugitive#statusline()}
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\

" adding vim-monokai theme
syntax enable
colorscheme monokai

" adding hybrid line numbers
set number relativenumber
